-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgavE9qmPVjW7d1sfv
fSvir3zuFCKta9hWrBX/L28DGTSgCgYIKoZIzj0DAQehRANCAAT3bq4XQOEf6rZN
KaAA/8sAzU3LKlaHpDHJZJyjmDJLY+dHCKZZIE4BJNiQHxdpOqPAOERaGJjqDchW
MBAWavuD
-----END PRIVATE KEY-----